### ISSUE TITLE
How to smooth out the edges of the insides of the black circle (Iris visualizer)

### ISSUE THREAD

**Issue by TowhidKashem** [tariqksoliman/Vissonance#14]
Hi @tariqksoliman, I really like the Iris visualizer you made! I'm comfortable with javascript but haven't worked much with Three JS, could you please tell me how to smooth out the edges of the black area here:

<img width="878" alt="Screenshot 2024-01-29 at 5 34 29 PM" src="https://github.com/tariqksoliman/Vissonance/assets/1139927/a2a8ccc7-270b-462e-a553-1185fbe96f29">

Basically I just want it to look the same as the outer blue ring and not have those cut rough edges. Would really appreciate it if you or someone reading this could give me a pointer with this. Thanks again!

**Comment by tariqksoliman** [comment]
Oh wow, I haven't looked at this repo in a long time. I might be able to help more this weekend but just looking at the code, it looks like we're looking out from inside a tube made out of 128 long PlaneGeometrys:
https://github.com/tariqksoliman/Vissonance/blob/master/scripts/visualizers/Iris.js#L52

Rendering iterates over them and only changes their position and color:
https://github.com/tariqksoliman/Vissonance/blob/master/scripts/visualizers/Iris.js#L93

My first thought to do what you want to is to, instead of having each long plane of the tube ending abruptly into the black background, to make the gradient on each plane go darkblue 0% -> cyan 90% -> black 90% -> black 100%. (The cyan 90% -> black 90% indicating a hard colorstop.)

Second thought, though with a less impressive contrast, would be to color the scene's background (black) to always match the color of the innermost "ring" (cyan).

Third thought is to, instead of 128 planes, actually use a cylinder geometry.

Fourth thought is to try increasing the number of planes of the tube (128) to something much higher: https://github.com/tariqksoliman/Vissonance/blob/master/scripts/visualizers/Iris.js#L12

**Comment by TowhidKashem** [comment]
> https://github.com/tariqksoliman/Vissonance/blob/master/scripts/visualizers/Iris.js#L52

ah thanks a lot for the help! I didn't think you'd see it given how old the repo is..So I tried 3 of the 4 changes by plugging your suggestions into chat GPT and assuming it made all the changes correctly these were the results:

#1:

<img width="911" alt="Screenshot 2024-01-29 at 9 39 52 PM" src="https://github.com/tariqksoliman/Vissonance/assets/1139927/767194d9-ec0b-4737-a760-f1af8bd4c1d5">

#2:

<img width="851" alt="Screenshot 2024-01-29 at 9 48 21 PM" src="https://github.com/tariqksoliman/Vissonance/assets/1139927/bea7f2b8-b120-4537-8495-214ee5df060f">

#4:

<img width="821" alt="Screenshot 2024-01-29 at 9 57 36 PM" src="https://github.com/tariqksoliman/Vissonance/assets/1139927/283e89b9-bd09-4eec-9247-4f9a5f04e72f">

I couldn't do #3 cause the code GPT gave me kept breaking. Obviously your suggestions might still be valid, I  just can't confirm cause I don't know threejs very well 😅

if you could spare a second this weekend or whenever you get the time I'd really appreciate it! absolutely no rush and worse case I will just use it as is cause it's still the best looking visualizer I could find! 🙏
